### ISSUE TITLE
single_main似乎未考慮depends？

### ISSUE THREAD

**Issue by renyuneyun** [archlinuxcn/lilac#110]
在調整其他時發現，`api.py`中的`single_main()`函數調用`lilac_build()`時未傳入`depends`參數。

所以這個意思是當使用`single_main()`時`depends = [...]`不會被考慮？還是說我漏掉了什麼東西？

**Comment by lilydjwg** [comment]
是的，因为它只打包这一个包嘛。

**Comment by yan12125** [comment]
用`./lilac 包名`就會考慮depends了～

**Comment by renyuneyun** [comment]
唔……好有道理的樣子……
那我就把issue關掉啦~
