### ISSUE TITLE
能添加一下包描述吗

### ISSUE THREAD

**Issue by dk333** [archlinuxcn/lilac#122]
能添加一下包描述吗?
这是用来干嘛的

**Comment by lilydjwg** [comment]
> Lilac is the build bot for archlinuxcn.

更详细的还没写……

**Comment by dk333** [comment]
> > Lilac is the build bot for archlinuxcn.
> 
> 更详细的还没写……你可以先看看[这个](https://github.com/archlinuxcn/lilac/blob/master/usage.rst)（有些过时）。

好吧。我关了。
