### ISSUE TITLE
Dangling `git_push` in lilac2/api.py

### ISSUE THREAD

**Issue by renyuneyun** [archlinuxcn/lilac#127]
在 `lilac2/api.py` 的第27行，有一個單獨成行且非調用的 `git_push`。

不知它在那是什麼用處？
我看 `cmd.py` 裏它是一個函數，所以好像這樣放在那沒任何用？

**Comment by lilydjwg** [comment]
用一下，满足 pyflakes。

**Comment by renyuneyun** [comment]
啊，原來如此……

怎麼感覺我好像以前問過這個問題的樣子……

沒有任何方法來調控pyflakes的這種報告/警告麼？

**Comment by lilydjwg** [comment]
没有办法的。我也没有找到其它的只检查可能的错误、不检查风格的检查器，所以只能这样了。
