### ISSUE TITLE
有关 BIND_MOUNTS

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#130]
目前 BIND_MOUNTS 只对 cargo 做了 cache，

然而 go 有 go 的 GOCACHE 和 GOPATH
另外对不同的架构 GOCACHE 和 GOPATH 还是不通用的。

可能将来其他还会有其他包的 cache

我觉得可以把 BIND_MOUNTS 去了，大家通过 makechrootpkg_args 自理？

**Comment by lilydjwg** [comment]
> 然而 go 有 go 的 GOCACHE 和 GOPATH

那就加上。

>  另外对不同的架构 GOCACHE 和 GOPATH 还是不通用的。

如果你不能在保持这两个环境变量不变的情况下编译不同架构的 Go 程序，请向 Go 的团队报告这个 bug。

> 可能将来其他还会有其他包的 cache

欢迎提出，然后咱们加上。

> 我觉得可以把 BIND_MOUNTS 去了，大家通过 makechrootpkg_args 自理？

采用率会很低。你看现在 rebuild 的支持加了这么久了，还是有很多包需要但是并没有采用。

**Comment by petronny** [comment]
> 如果你不能在保持这两个环境变量不变的情况下编译不同架构的 Go 程序，请向 Go 的团队报告这个 bug。

这个我还真不清楚了。。。基本不用 go，不太清楚 go 编译的cache是以什么为标准的。

那就默认来个 gocache 然后其他架构的 makechrootpkg_args 自理吧。。。

一个是 GOPATH 需要映射 ${HOME}/go:/build/go
一个是 GOCACHE 需要映射 ${HOME}/.cache/go-build:/build/.cache/go-build
