### ISSUE TITLE
以附件形式发送 log

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#135]
如题，既然现在每个包的log都已经独立了，我们是不是可以把同一维护者的报错log汇总一下，以附件的形式在一封邮件里发送给维护者？

目的是为了减少发送邮件的数量，每一个维护者只发一封邮件。

**Comment by lilydjwg** [comment]
每个包分开发送有以下优点：

* 及时
* 不受后续错误的影响
* 易于检索
* 不太容易受到邮件大小限制
