### ISSUE TITLE
.sig for -debug package not copied

### ISSUE THREAD

**Issue by yuyichao** [archlinuxcn/lilac#139]
`freecad-oce-debug-0.18.16148-12-x86_64.pkg.tar.xz.sig` is in `~/repo` but is not copied to the repo. The corresponding file for the non -debug package got copied just fine.

Also, somehow the package got deleted and I had to upload it again...

**Comment by lilydjwg** [comment]
The directory name is freecad but the package name is freecad-oce, so it's getting deleted.
