### ISSUE TITLE
如果一个包编译失败了,nvtake也会把其更新到oldver中

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#14]
就是lilac中的379-380行

```
if need_update:
    run_cmd(['nvtake', nvchecker_file] + list(need_update))
```

是不是应该改成:

```
if update_succeeded:
    run_cmd(['nvtake', nvchecker_file] + list(update_succeeded))
```

?

**Comment by lilydjwg** [comment]
On Fri, Aug 26, 2016 at 12:03:12AM -0700, Jingbei Li wrote:
> 就是lilac中的379-380行
> ```
> if need_update:
>     run_cmd(['nvtake', nvchecker_file] + list(need_update))
> ```
> 是不是应该改成:
> ```
> if update_succeeded:
>     run_cmd(['nvtake', nvchecker_file] + list(update_succeeded))
> ```
> ?

我记得以前是这样子的。

一般来说，一个版本的包编译失败了，下次再编译还是会失败的。只有更新之后
lilac 才会再次尝试编译。

-- 
Best regards,
lilydjwg

Linux Vim Python 我的博客:
http://blog.lilydjwg.me/
-- 
A: Because it obfuscates the reading.
Q: Why is top posting so bad?

**Comment by petronny** [comment]
原来如此

**Comment by petronny** [comment]
这个可不可以做成一个选项。。
叫是否尝试重复编译之类的。。

**Comment by petronny** [comment]
还有一个问题，就是中间ctrl-c了
会把所有还没来得及编译的包都nvtake了

**Comment by lilydjwg** [comment]
是么？求修～

**Comment by lilydjwg** [comment]
Ctrl-C 的支持一直有问题的。

**Comment by xgdgsc** [comment]
问下像rstudio-desktop-bin之前2天都有一次编译失败，给我发了邮件，我补充了依赖，怎么手动让lilac再尝试编译这个包。

**Comment by lilydjwg** [comment]
@xgdgsc 如果你修改了文件的话，lilac 会自动重新尝试的。
