### ISSUE TITLE
Please do not commit pkgver-only bumps to -git packages

### ISSUE THREAD

**Issue by eli-schwartz** [archlinuxcn/lilac#146]
By longstanding policy, AUR users are *firmly* discouraged from committing and publishing PKGBUILD updates which merely update the `pkgver=` and/or `pkgrel=` variables in a PKGBUILD which contains a `pkgver()` function and builds from a git branch.

The result of this sort of thing looks like this (which turns out to be done by lilac, oh no!): https://aur.archlinux.org/cgit/aur.git/log/?h=servo-git

I dare you to figure out which commits there are useful and actually change something. :p

Please update lilac to detect when there are no changes in a https://github.com/archlinuxcn/repo commit other than bumping the version in a VCS package, and refrain from publishing it to the AUR. If this is not possible, please remove lilac functionality from all VCS packages, and commit them manually after human review.

**Comment by yan12125** [comment]
Some changes that should not be pushed to AUR:

1. pkgver bump for VCS packages
2. pkgrel bump for both VCS and non-VCS packages (e.g. rebuild for soversion bumps)

Anything else?

**Comment by yan12125** [comment]
I proposed #147 to fix the issue for all packages using update_aur_repo().

**Comment by eli-schwartz** [comment]
Thanks, that looks like a nice solution. :)

**Comment by soloturn** [comment]
@eli-schwartz, unrelated to this ticket, i was updating a git version manual recently, as upstream fixed some bugs, so i thought this changed something for a user of the package. i got referred to here, as updating the version only is bad dju dju: https://aur.archlinux.org/packages/cosmic-epoch-git. how is this policy lived in practice?
