### ISSUE TITLE
lilac无法添加那些package base与包不同名的包为依赖

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#15]
比方说，lilac.py中指明了
```
depends=['python2-a']
```
python2-a与python-a由同一个PKGBUILD打出来的，package base叫a
所以我在repo中添加了a/PKGBUILD及a/package.list
```
python-a
python2-a
```
但是此时lilac.py的check_depends中的_check_dir无法检测到python2-a这个文件夹
于是就报错了

**Comment by petronny** [comment]
虽说我建一个叫python2-a的空文件夹就能解决这个问题
但是感觉有点奇怪

**Comment by lilydjwg** [comment]
```
depends = [('a', 'python2-a')]
```

**Comment by lilydjwg** [comment]
PS: `package.list` 不是 lilac 需要的，而是包清理脚本需要的。

**Comment by petronny** [comment]
原来如此
