### ISSUE TITLE
Add a license statement

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/lilac#161]
To properly package lilac, a license statement is needed. There are two different levels of formality to do this:

1. The less formal way - @lilydjwg picks some license and commits a LICENSE file

2. The formal way. I consider chaging from no license ("All Rights Reserved") to some specific license as some kind of relicensing, so we need to establish an agreement from all previous contributors [1]. Here is an example: [2].

[1] https://github.com/archlinuxcn/lilac/graphs/contributors
[2] https://github.com/mpv-player/mpv/issues/2033

**Comment by lilydjwg** [comment]
I'd like to use GPLv3 for this project. What do others think?

**Comment by yan12125** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by yan12125** [comment]
Ping other contributors

@MarvelousBlack
@SilverRainZ
@VOID001
@Xuanwo
@a-wing
@attenuation
@axionl
@bennyyip
@cuihaoleo
@farseerfc
@felixonmars
@lilacbot (?)
@petronny
@renyuneyun
@yuyichao
@zsrkmyn

lilacbot has a commit c990c5d67e10939b8e85b95e46ea00b7227c5e40. @lilydjwg Is that authored by you?

**Comment by felixonmars** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by petronny** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by yan12125** [comment]
> Checkbox for "I'm fine with using GPLv3 for my prior contributions.":

Well, most of packagers do not have write access to this repo, and thus modifying others' comments is not allowed.

**Comment by lilydjwg** [comment]
> lilacbot has a commit [c990c5d](https://github.com/archlinuxcn/lilac/commit/c990c5d67e10939b8e85b95e46ea00b7227c5e40). @lilydjwg Is that authored by you?

Yes. I forgot to explicitely use my name to commit on the build machine.

**Comment by farseerfc** [comment]
I'm fine with using GPLv3 for my prior contributions.
(Explicit statement because I cannot change the checkbox)

**Comment by MarvelousBlack** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by Xuanwo** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by yuyichao** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by SilverRainZ** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by bennyyip** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by zsrkmyn** [comment]
I think there are only spaces and empty lines are left as my contributions. For these spaces and empty lines, I'm fine with GPLv3.

If there are anything else contributed by me, I'm fine with GPLv3 for them as well.

**Comment by yan12125** [comment]
@zsrkmyn A large portion of your valuable contributions to usage.rst is still present in the latest commit (107835f2fb9409a3356dbbea45e578210da39818) [1] and it does provide great information for those who are interested in lilac like me :)

[1] https://github.com/archlinuxcn/lilac/blame/107835f2fb9409a3356dbbea45e578210da39818/usage.rst

**Comment by axionl** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by a-wing** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by VOID001** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by attenuation** [comment]
I'm fine with using GPLv3 for my prior contributions.

**Comment by yan12125** [comment]
@renyuneyun could you have a look at this?

**Comment by renyuneyun** [comment]
I'm fine with using GPLv3 for my prior contributions.

(Sorry I didn't check github notifications, and the emails went to a strange place...)

**Comment by yan12125** [comment]
> Sorry I didn't check github notifications, and the emails went to a strange place...

No problem!

---

@cuihaoleo mind to have a look? Your prior contribution is https://github.com/archlinuxcn/lilac/commit/1f81d456d16add2481a2f25723abee32bd96c0ee, and it's still used in today's lilac: https://github.com/archlinuxcn/lilac/blob/f7f64db993c681629a2efa1b24b87bf8995014b8/lilac2/api.py#L425-L440.

**Comment by cuihaoleo** [comment]
I'm fine with using GPLv3 for my prior contributions!!!

**Comment by yan12125** [comment]
Thanks everyone for the agreement! Now that it is OK to relicense this project as GPLv3: #170.
