### ISSUE TITLE
add_xxx functions break string substitutions

### ISSUE THREAD

**Issue by DDoSolitary** [archlinuxcn/lilac#164]
For example, the [`lib32-fltk`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lib32-fltk) AUR package has `"${pkgname#lib32-}"` in its `depends` array. If I call `add_depends()` when building this package, it goes broken because the double quotes are blindly replaced by single quotes by `_add_into_array`.

**Comment by DDoSolitary** [comment]
One quick but ugly solution: always use double quotes in `_add_into_array`. I guess it is OK because it is very unlikely that a package has special characters in its dependencies.

Or we need rewrite the parsing part to save the quotes used in the original file.

**Comment by lilydjwg** [comment]
Switching to double quotes sounds fine to me.
