### ISSUE TITLE
Does lilac work with docker/ansible

### ISSUE THREAD

**Issue by SolarAquarion** [archlinuxcn/lilac#169]

**Comment by lilydjwg** [comment]
By "work with docker", do you mean that you have another distro other than Arch and want to run lilac inside an Arch container?

I don't understand what "work with ansible" would mean.

**Comment by petronny** [comment]
lilac doesn't have published docker image.

> I don't understand what "work with ansible" would mean.
ansible is https://www.ansible.com/ .

lilac doesn't have ansible module or API.

**Comment by lilydjwg** [comment]
I know what ansible is. I don't know why anything special needs to be done on lilac side to "work with ansible". It's just a normal cron job (or use systemd.timer, etc).

**Comment by SolarAquarion** [comment]
The question is I guess, is "What is the setup" of lilac and whatever on the build server's.

**Comment by petronny** [comment]
lilac will be packaged as an arch package also as a pypi package after #161 is solved.

**Comment by SolarAquarion** [comment]
There will probably need to be some documentation on how to spin up your own build server with lilac if wanted, but it can probably be just a build bot on your own server just as well.

**Comment by lilydjwg** [comment]
I've updated the README file in this repo. It's not very detailed but I hope it helps.

**Comment by SolarAquarion** [comment]
One more question Concerning wine-tkg/linux-tkg https://github.com/Frogging-Family/linux-tkg and https://github.com/Frogging-Family/wine-tkg-git basically these PKGBUILD's and system turns 1 PKGBUILD into 10 different PKGBUILDS based on the configuration you chose.  I don't think lilac supports the system of building PKGBUILD for each variation of it based on configurations you give in.  Or can it be done via the yaml?

**Comment by lilydjwg** [comment]
Well, you can create copies of it and build each variant you want in a subdirectory. lilac only supports one subdirectory with one devtools build command.

**Comment by SolarAquarion** [comment]
then you can just proc nvchecker for build updates

**Comment by aviallon** [comment]
In my case, I want to run lilac in a container to increase security when building lots of AUR packages. It'll also be easier to setup on multiple nodes, and I don't want to use a VM for that.

**Comment by lilydjwg** [comment]
There shouldn't be obstacles to run lilac in a container, as long as you setup lilac. I'm not good as writing Dockerfile though. Maybe I could try that when I have time, but maybe I won't have that time...
