### ISSUE TITLE
recv_gpg_keys: use another key server than keys.gnupg.net

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/lilac#178]
Currently, [recv_gpg_keys](https://github.com/archlinuxcn/lilac/blob/master/recv_gpg_keys) tries `hkp://keys.gnuph.net`. That domain is not a real domain name but [a hard-coded mapping](https://dev.gnupg.org/source/gnupg/browse/master/dirmngr/server.c;gnupg-2.2.29$2127) in gnupg. Currently, the build server has gnupg-2.2.28, in which `hkp://keys.gnupg.net` is mapped to `hkp://hkps.pool.sks-keyservers.net`, and the latter is gone. As a result, fetching GPG keys [may fail](https://build.archlinuxcn.org/~imlonghao/log/dnsviz/2021-07-21T12%3A17%3A02.html):
```
gpg: 从公钥服务器接收失败：无名称
```
gnupg-2.2.29 [updates the mapping](https://dev.gnupg.org/rG47c4e3e00a7ef55f954c14b3c237496e54a853c1) to a working server, so a short term fix can be updating rge server. In the long term, I suggest to switch to another key server, so that debugging GPG issues is easier, and development of GnuPG will not affect lilac.

**Comment by lilydjwg** [comment]
Thanks. I didn't know that it's not a real server.

**Comment by yan12125** [comment]
Thanks! I didn't know that until yesterday, either :P
