### ISSUE TITLE
Document for English

### ISSUE THREAD

**Issue by Hayao0819** [archlinuxcn/lilac#180]
I'm trying to build a repository using packages that I can't put in my AUR with lilac.
I want to read the documentation on how to use it, but I don't understand Chinese. 
I'm currently using Google Translate, but consider creating an English document in the future.

**Comment by lilydjwg** [comment]
The setup doc is already in English. wrt how to use, there is not that many docs anyway. You may just to try mimic existing packages in archlinuxcn/repo.

The error message is in Chinese, which I think is a bigger i18n issue.

**Comment by starsareintherose** [comment]
Hello, maybe try to follow the command in the Chinese documents. https://bioarchlinux.github.io/wiki/zh/deploy/
And I am delighted to help you via email or IRC or telegram.

**Comment by starsareintherose** [comment]
https://bioarchlinux.github.io/wiki/en/deploy/ hopefully, it can help you

**Comment by lilydjwg** [comment]
A preliminary setup doc has been available: https://lilac.readthedocs.io/en/latest/setup.html
