### ISSUE TITLE
Does not run when python-pygitgub is installed

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/lilac#183]
When [python-pygithub](https://archlinux.org/packages/community/any/python-pygithub/) is installed, lilac crashes at startup:
```
Traceback (most recent call last):
  File "/usr/bin/lilac", line 52, in <module>
    from lilac2.repo import Repo
  File "/usr/lib/python3.10/site-packages/lilac2/repo.py", line 14, in <module>
    from github import GitHub
ImportError: cannot import name 'GitHub' from 'github' (/usr/lib/python3.10/site-packages/github/__init__.py)
```

I got this issue from the lilac-git package, and I believe in-tree lilac is also affected.

A simple fix may be using `sys.path.insert` instead of [`sys.path.append`](https://github.com/archlinuxcn/lilac/blob/97ed68d8d0044d2deacc2a837eacd2167e0df18c/lilac#L34) in lilac. A better fix may be moving vendored stuffs into a `winterpy` namespace (ex: `from winterpy.github import GitHub`).

**Comment by lilydjwg** [comment]
I moved the path to the front. It's too late to move them into a namespace without dissassociating with winterpy.

**Comment by yan12125** [comment]
Thanks! It's fine as long as it works :)
