### ISSUE TITLE
Support for invoking commands when a build succeeded / failed.

### ISSUE THREAD

**Issue by moodyhunter** [archlinuxcn/lilac#190]
I'm using a custom command to send out messages (the same way as `notify-send`).

It seems that lilac only sends emails when a package fails to be built, but can't invoke commands during such incidents.

It'll be very helpful if command hooks can be supported :)

**Comment by petronny** [comment]
take a look at post-build-always?

**Comment by moodyhunter** [comment]
thanks :)
