### ISSUE TITLE
[Help] Enter a lilac user

### ISSUE THREAD

**Issue by Hayao0819** [archlinuxcn/lilac#194]
Hello. I am Hayao0819 who requested English documentation in #180.
Thank you for doing the work for users who cannot read Chinese.

After that I was not able to work on it for a while due to my academic commitments.
I have just resumed working on building a Lilac server.
I wrote a PKGBUILD and prepared a lilac.yaml.　
I built a pure Arch Linux and installed the dependencies for lilac according to this tutorial.

The lilac configuration in the documentation says to log in to the user for lilac using machinectl and not to use su or sudo.
However, as far as I know, machinectl is for container management, which I cannot do because I do not have a single container.

Here is the error I get from actually running the command

```
hayao@Hayao-SZ5 ~> machinectl shell lilac@
Failed to get shell PTY: Access denied
hayao@Hayao-SZ5 ~ [1]> 
```

Does lilac need to be run in the nspawn container?

Thank you.

**Comment by lilydjwg** [comment]
Well, you need `sudo` before `machinectl`. machinectl can be used for a local login too, and it sets up the correct session environment (e.g. a `systemd --user` instance).

**Comment by Hayao0819** [comment]
Thank you so much for helping me. It works correctly.

I did not know the usage of machinectl.

It is tiny mistake of me but I was helped that. I can continue setup. 

However I have another error in my lilac server so I will make another new issue.
