### ISSUE TITLE
参数功能汇总

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#28]
就是列一下要写哪些。。目前已知的有

* -c , --config 指定config.ini
* --no-git-push
* --no-send-mail

还有啥

**Comment by lilydjwg** [comment]
我觉得能指定配置文件就够了呢

**Comment by petronny** [comment]
有些能override的可以方便调试？

**Comment by farseerfc** [comment]
題外話， github 的新 projects 功能是不是做這種計劃的……

**Comment by lilydjwg** [comment]
哦。我一般不调试 lilac 的……

@farseerfc 不知道呢，github 突然改了不少，我也没收到更新通知 :-(

**Comment by farseerfc** [comment]
@lilydjwg 開了一個 project 寫了點我覺得需要做的，這樣如何？

**Comment by lilydjwg** [comment]
@farseerfc 这个 Project，是 GitHub 版的 Trello 么……

**Comment by petronny** [comment]
这难道不是zenhub么。。。

**Comment by farseerfc** [comment]
沒用過 trello 和 zenhub ……但是大概就是跟蹤這種 idea 的進度的吧
