### ISSUE TITLE
write a setup.py

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/lilac#35]

**Comment by yan12125** [comment]
Hmmm https://pypi.org/project/lilac/

How about calling it lilac2 in `setup.py`? Otherwise `pip list --outdated` will complain.

**Comment by petronny** [comment]
archlinuxcn-lilac ?

**Comment by yan12125** [comment]
I created #160. If that PR is merged, the next thing is adding a LICENSE to this repo so that lilac can be packaged downstream.
