### ISSUE TITLE
Should lilac do a clean up after `makepkg -od`?

### ISSUE THREAD

**Issue by zsrkmyn** [archlinuxcn/lilac#39]
I encountered a problem yesterday that the moe lilac sent me a e-mail to remind me the that vim-youcompleteme-git was failed to build AGAIN! The error occured while runing `makepkg -od`.

I did a research and found it was mainly due to the existing of the old `$srcdir` generated by last runing of `makepkg -od`, and a patch was applied twice:
```
==> 正在开始 prepare()...
  -> Setting up Git submodules...
patching file YouCompleteMe/autoload/youcompleteme.vim
patching file ycmd/default_settings.json
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file ycmd/default_settings.json.rej
==> 错误： 在 prepare() 中发生一个错误。
    正在放弃...
```

Since the file to be patched is actually in a git submodule, It keeps patched (but not reset to the origin one at the process of extracting sources) at the second time `makepkg -od` running. The submodule in PKGBUILD is initialized as the [wiki](https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git_Submodules) says.

I think about some solutions, but don't know which is best:
- Force clean up the submodule dircetories before `git submodule init` in PKGBUILD. However, this is unnacessary in most cases and may make PKGBUILD a little bit confusing.
- Clean up the `$srcdir` (or more specifically, remove it) in `lilac.py`. However, due to the different setting of `BUILDDIR` in `~/.makepkg.conf` or `/etc/makepkg.conf`, it is not easy to obtain the location where the `$srcdir` is.
- Use `makepkg -od --noprepare` [here](https://github.com/archlinuxcn/lilac/blob/master/lilaclib.py#L319). This is a bit tricky and since `pkgver()` is executed after `prepare()`, `pkgver` may be wrongly acquired by lilac due to the skip of `prepare()`.
- Use `makepkg -odc` at the line mentioned above. This force `makepkg` remove the `$srcdir` after obtaining the sources and running `pkgver()` to update PKGBUILD. (I prefer this)

So, which one is preferable?

**Comment by lilydjwg** [comment]
`-c` will clean up **after** the operation.

I'll try to remove the `src` directory.
