### ISSUE TITLE
当pkgrel的值带有引号时，pkgrel不能正确比较大小

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#40]
比如在[keras的PKGBUILD中](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-keras)中
```
pkgrel="1"
```
如果通过修改成下面任意
```
pkgrel=1.1
pkgrel="1.1"
```
来trigger rebuild，build出来的都是
```
pkgrel="1"
```
archrepo2也不会识别rebuild出来的包

通过lilac.py去掉引号也是如此

**Comment by lilydjwg** [comment]
再试试看呢？

**Comment by petronny** [comment]
Okay了，多谢~
