### ISSUE TITLE
有关vcs_update中的makepkg -od

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#54]
https://github.com/archlinuxcn/lilac/blob/76cde381fc557d1e9ca1833da7b3da6be137e832/lilaclib.py#L318
这个是打算仅下载文件的意思吗？

就是现在其实会运行pkgver()和prepare()，但实际上需要吗？

**Comment by lilydjwg** [comment]
是啊，仅仅需要更新文件而已。

**Comment by petronny** [comment]
那是不是可以`makepkg --verifysource`呢
我试了一下这个不会运行运行pkgver()和prepare()
不过会产生一个空的src目录

**Comment by lilydjwg** [comment]
好像是需要 pkgver 的耶，不然 PKGBUILD 里的版本号怎么更新呢？

**Comment by lilydjwg** [comment]
close as inactive.
