### ISSUE TITLE
有关git add 被ignore的文件时的报错

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#57]
https://github.com/archlinuxcn/lilac/blob/master/lilaclib.py#L253
除了添加.gitignore中的文件外，
还有其他可能会出错吗

另外我觉得这些文件是不是没添加上也ok呢？
就是说except里直接pass可不可以呢

**Comment by axionl** [comment]
直接在包目录下手动添加 .gitignore

例如
```
# repo/package/.gitignore
!*.html
```

**Comment by axionl** [comment]
还是手动添加到包目录下的 .gitignore 比较好，例如：

```
# repo/package/.gitignore

!*.html
```
