### ISSUE TITLE
recv_gpg_keys() goes wrong in single_main mode.

### ISSUE THREAD

**Issue by zsrkmyn** [archlinuxcn/lilac#6]
Here is the traceback:
```
[D 01-20 18:19:43.732 lilaclib:386] running ['recv_gpg_keys'], not using pty, showing output
Traceback (most recent call last):
  File "lilac.py", line 13, in <module>
    single_main()
  File "/home/stephen/worktmp/lilac_test/lilaclib.py", line 380, in single_main
    accept_noupdate = True,
  File "/home/stephen/worktmp/lilac_test/lilaclib.py", line 282, in lilac_build
    recv_gpg_keys()
  File "/home/stephen/worktmp/lilac_test/lilaclib.py", line 453, in recv_gpg_keys
    run_cmd(['recv_gpg_keys'])
  File "/home/stephen/worktmp/lilac_test/lilaclib.py", line 394, in run_cmd
    p = subprocess.Popen(cmd, stdout = stdout, stderr = subprocess.STDOUT)
  File "/usr/lib/python3.4/subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1456, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'recv_gpg_keys'
```

And here, I find a way to solve it:
```
diff --git a/lilaclib.py b/lilaclib.py
index b3a3c21..f9f47e7 100644
--- a/lilaclib.py
+++ b/lilaclib.py
@@ -450,4 +450,4 @@ def build_prefix_to_arch(cmd):
     return 'x86_64'
 
 def recv_gpg_keys():
-  run_cmd(['recv_gpg_keys'])
+  run_cmd([os.path.join(os.path.realpath(os.path.dirname(__file__)), 'recv_gpg_keys')])
```

**Comment by lilydjwg** [comment]
Prepend the path to `$PATH` is better :-)

**Comment by lilydjwg** [comment]
Will the following patch resolve the problem for you?

diff --git a/lilaclib.py b/lilaclib.py
index 1979808..b96b1e2 100644
--- a/lilaclib.py
+++ b/lilaclib.py
@@ -369,6 +369,7 @@ def find_local_package(repodir, pkgname, arch):
         return os.path.abspath(ret)
 
 def single_main(build_prefix='makepkg'):
+  prepend_self_path()
   enable_pretty_logging('DEBUG')
   lilac_build(
     build_prefix = build_prefix,
@@ -378,6 +379,11 @@ def single_main(build_prefix='makepkg'):
     accept_noupdate = True,
   )
 
+def prepend_self_path():
+  mydir = os.path.realpath(os.path.dirname(__file__))
+  path = os.environ['PATH']
+  os.environ['PATH'] = mydir + os.pathsep + path
+
 def run_cmd(cmd, *, use_pty=False, silent=False):
   logger.debug('running %r, %susing pty,%s showing output', cmd,
                '' if use_pty else 'not ',

-- 
Best regards,
lilydjwg

**Comment by zsrkmyn** [comment]
@lilydjwg , Yes, the patch works fine! Thanks.
