### ISSUE TITLE
增加文件編輯（常用）工具函數

### ISSUE THREAD

**Issue by renyuneyun** [archlinuxcn/lilac#62]
之前在寫倉庫中的lilac.py的時候，時不時會碰到PKGBUILD中部分變量（主要是`depends`和`mekedepends`）不正確/完整的問題。
雖說理論上應該等上游（對於我的幾例來說就是AUR）修改，但有時候上游修改太慢，所以有時直接就在lilac.py中修改了，直到上游修正再改回去。

這樣，那部分工具函數就要複製過來過去地，稍顯累贅。故而想是否可以將其加入lilac代碼庫中，以便重用、訂正以及更多人使用。

[這裏](https://github.com/renyuneyun/lilac/blob/utils/lilac2/utils.py)基本上是直接將之前用的代碼複製過來，並增加了兩個入口函數（`add_depends`和`add_makedepends`）。

如果認爲可以合併的話，現在還有兩個問題：
1. 這個文件應該放在哪，以及叫什麼？
2. 是否應該在次級模塊中引用lilaclib？或者是將被引用的那個函數（`edit_file`）移至（另一個？）次級模塊中的某個地方？

**Comment by renyuneyun** [comment]
當然，其實我最好奇的是：有沒有哪個python庫可以直接編輯shell腳本，並且還可以輸出回去的啊？……
有的話就這個提議就可以直接關閉了，正好我也可以改用它。

**Comment by lilydjwg** [comment]
可以放在 lilac2.pkgbuild 模块里，然后在 lilac2.api 里引入给 lilac.py 用的函数（目前还要在 lilaclib.py 里再引入一次；lilaclib 会逐渐被拆分掉）。
