### ISSUE TITLE
Feature Request: 自动添加optdepends到makedepends

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#67]
AUR上的很多包的某些支持都是只写optdepends的
如果能自动加到makedepends就能打开这些支持
作为binary源应该还是默认打开所有支持的吧？

**Comment by yuyichao** [comment]
这属于为了写的不对的 PKGBUILD 让正确的 PKGBUILD 不能正常工作了. 如果 AUR 为了源码编译方便缺少 makedepends 的话只要支持在 lilac.py 里面另加编译依赖就好, 不应该从 optdepends 猜.

**Comment by lilydjwg** [comment]
可以添加一个将 optdepends 添加到 makedepends 的 API，由 lilac.py 自行决定是否使用。
