### ISSUE TITLE
[Feature request]使updpkgsum变成update_pkgver_and_pkgrel的可选项

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/lilac#74]
我手上有些包可以从网上自动下载sum...比如说类似于这样的PKGBUILD

_sha1="$(curl https://www.giss.nasa.gov/tools/panoply/download/Panoply-${pkgver}.sha1.txt 2>/dev/null | grep 'PanoplyJ.*.zip' | grep -o '^[^ ]*')"
sha1sums=("${_sha1}"
...
update_pkgver_and_pkgrel貌似会强制makepkg -g 然后updpkgsum，不知道可不可以让它变成可选项。默认还是自动updpkgsum啦，但是如果能够给定一个参数的话，可以只update pkgver，不update sum

**Comment by lilydjwg** [comment]
加上了，加参数 updpkgsums=False 即可。

**Comment by heavysink** [comment]
谢谢！
