### ISSUE TITLE
[讨论] lilac的Logo

### ISSUE THREAD

**Issue by TobiichiAmane** [archlinuxcn/lilac#77]
我的朋友Canplayer（昵称）决定为lilac设计一组Logo。现在草案有如下几个（原谅我没有整齐地排列它们），有建议、抑或需要完全重新设计可以提出，也请一同决定最后的Logo样式。Logo暂定为CC-BY 3.0协议。
![image](https://user-images.githubusercontent.com/14824064/47075696-9f238080-d22f-11e8-8cbf-ff2b9a1f410f.png)

-------------------------分割线-------------------------
@lilydjwg @MarvelousBlack @OriginCode 朋友给加了包之后是这样
![image](https://user-images.githubusercontent.com/14824064/47085906-aa37da00-d24a-11e8-9f43-0941dc25f05e.png)

-------------------------分割线-------------------------
使用打包丝带的版本：
![image](https://user-images.githubusercontent.com/14824064/47093120-16bad500-d25b-11e8-8a27-65ec95273595.png)

**Comment by TobiichiAmane** [comment]
我个人比较倾向于最后一个？你们怎么看（

**Comment by a-wing** [comment]
第一个和第二个感觉不好（

觉得第三个和第五个比较好看（

**Comment by MarvelousBlack** [comment]
第三個好看，第五個看起來細節多一點

**Comment by farseerfc** [comment]
第五個 +1

**Comment by attenuation** [comment]
第三个好看啊！

**Comment by TobiichiAmane** [comment]
> 我喜欢第三个。不过中间要不要放个包？

放个，，包？什么包（

**Comment by lilydjwg** [comment]
打包的盒子？类似 Dropbox 那样的。

**Comment by TobiichiAmane** [comment]
> 打包的盒子？类似 Dropbox 那样的。

我，，我问问我的朋友能不能做（

**Comment by OriginCode** [comment]
第三個和第五個不錯的樣子
還是如肥貓所說，能否加一個“包”的圖示😃

**Comment by MarvelousBlack** [comment]
加個包

**Comment by TobiichiAmane** [comment]
结果已确定。
