### ISSUE TITLE
发生未知错误！NameError: name 'bp' is not defined

### ISSUE THREAD

**Issue by xgdgsc** [archlinuxcn/lilac#9]
好几个软件包(anaconda, docear, cppreference-qt, android-sdk-build-tools) 4:40 PM收到lilac发的错误邮件，内容都一样：

发生未知错误！调用栈如下：

Traceback (most recent call last):
  File "/home/lilydjwg/bin/lilac", line 89, in build_package
    depends = DEPENDS.get(package, ()),
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 351, in lilac_build
    call_build_cmd(bp, depend_packages, pkgs_to_build)
NameError: name 'bp' is not defined

不知道是不是已经修复？

**Comment by lilydjwg** [comment]
On Sat, Apr 18, 2015 at 05:17:53AM -0700, xgdgsc wrote:
> 好几个软件包(anaconda, docear, cppreference-qt, android-sdk-build-tools) 4:40 PM收到lilac发的错误邮件，内容都一样：
> 
> 发生未知错误！调用栈如下：
> 
> Traceback (most recent call last):
>   File "/home/lilydjwg/bin/lilac", line 89, in build_package
>     depends = DEPENDS.get(package, ()),
>   File "/home/lilydjwg/soft/lilac/lilaclib.py", line 351, in lilac_build
>     call_build_cmd(bp, depend_packages, pkgs_to_build)
> NameError: name 'bp' is not defined
> 
> 不知道是不是已经修复？

这个问题已经修复了 ;-)

lilac 今天有比较大的改动，所以出现了很多错误。

-- 
Best regards,
lilydjwg
