### ISSUE TITLE
有关直接同步其他地方的binaries到repo

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#93]
如 https://github.com/archlinuxcn/repo/issues/929
除此之外我还见过某些包有不提供PKGBUILD只提供arch binaries的。

1. 我们可以直接同步这些包到repo吗？
1. 若可以，我们应如何实现呢？
lilac.py直接下载可否？
1. 对于已签名的包，直接添加key是否可以？
对于未签名的包，我们是否要签名一次？

**Comment by lilydjwg** [comment]
我觉得镜像别的仓库的包这种功能不应该属于这个项目。倒是可以开一个项目专门用于镜像单独的软件包。

**Comment by yan12125** [comment]
User想用什麼庫，直接加pacman.conf不就得了？

**Comment by petronny** [comment]
有的在墙外，比较麻烦

**Comment by yan12125** [comment]
抱歉沒在牆內待過，沒想到這點...

技術上來說，這應該比較接近archrepo2的業務範圍。寫個script把binary repo裡的檔案抓下來，再丟進編譯機上的repo/資料夾應該就行了。

**Comment by lilydjwg** [comment]
我倾向于单独弄一个仓库给这些包。

**Comment by petronny** [comment]
嗯，分一个仓库也挺好的。听安排了

**Comment by lilydjwg** [comment]
想了一下，分一个仓库的话，需要做以下事情：

* [ ] 新的 archrepo2 服务
* [ ] 配置文件的管理
* [ ] 检查仓库更新并下载（相当于 pacman -Syuw；不知道 pyalpm 能不能做）
* [ ] 文档与宣传

签名的话，使用源仓库现成的。如果没有就没有，lilac 再加一个签名并没有多大用处。

**Comment by yan12125** [comment]
> 不知道 pyalpm 能不能做

我用了幾次pyalpm，經驗是pacman一行可以做的事pyalpm常常得寫好多行

**Comment by petronny** [comment]
那签名问题呢？

**Comment by lilydjwg** [comment]
签名得用户自己导入、信任了。本来这个的安全性和信任关系就很成问题……

**Comment by petronny** [comment]
就是只负责同步包是吧，也好
