### ISSUE TITLE
Lilac doesn't resolve dependencies recursively

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/lilac#95]
This is how current Lilac resolves dependencies:

https://github.com/archlinuxcn/lilac/blob/87465706360168f3a0cce49cb68f8aafd8ca5dff/lilac2/building.py#L53-L61

It cannot resolve dependencies more than two layers. An example is lxqt-panel-git, whose dependency tree is:

```
lxqt-panel-git
  lxqt-globalkeys-git
    liblxqt-git
      libqtxdg-git
  libsysstat-git
```

A solution (workaround?) is using `archlinux-x86_64` as the build prefix.

---

看了下Lilac的代碼，修好這個問題似乎得改不少地方，因此先開個坑，有空再研究。

**Comment by lilydjwg** [comment]
不会啊，这种情况是支持的：

<details>
<summary>test-lilac-dep.py 代码</summary>

```py
#!/usr/bin/env python3

from pathlib import Path

from lilac2.packages import get_dependency_map, DependencyManager
from lilac2 import lilacpy

def main():
  repodir = Path('/ldata/src/archgitrepo')
  mods, _ = lilacpy.load_all(repodir)
  depman = DependencyManager(repodir)
  m = get_dependency_map(depman, mods)
  for d in m['lxqt-panel-git']:
    print(d)

if __name__ == '__main__':
  from nicelogger import enable_pretty_logging
  enable_pretty_logging('DEBUG')
  main()
```
</details>

结果：

```
>>> py test-lilac-dep.py
Dependency(pkgdir=PosixPath('/ldata/src/archgitrepo/libsysstat-git'), pkgname='libsysstat-git')
Dependency(pkgdir=PosixPath('/ldata/src/archgitrepo/lxqt-globalkeys-git'), pkgname='lxqt-globalkeys-git')
Dependency(pkgdir=PosixPath('/ldata/src/archgitrepo/liblxqt-git'), pkgname='liblxqt-git')
Dependency(pkgdir=PosixPath('/ldata/src/archgitrepo/libqtxdg-git'), pkgname='libqtxdg-git')
Dependency(pkgdir=PosixPath('/ldata/src/archgitrepo/lxqt-build-tools-git'), pkgname='lxqt-build-tools-git')
```

依赖解析的代码在这里：

https://github.com/archlinuxcn/lilac/blob/c2dbbcca6371a38d76f630d57e24a9933c5dfb59/lilac2/packages.py#L10-L29

**Comment by petronny** [comment]
（那块折叠的是什么语法啊。。。）

**Comment by yan12125** [comment]
Hmm 那我研究下為啥Lilac的指令沒有包含libqtxdg-git
<pre>
命令执行失败！

命令 ['extra-x86_64-build', '--', '-I', PosixPath('/home/lilydjwg/archgitrepo/libsysstat-git/libsysstat-git-0.4.1.4.gef0e4de-1-x86_64.pkg.tar.xz'), '-I', PosixPath('/home/lilydjwg/archgitrepo/lxqt-globalkeys-git/lxqt-globalkeys-git-0.13.0.76.g7ac6ecb-1-x86_64.pkg.tar.xz'), '-I', PosixPath('/home/lilydjwg/archgitrepo/liblxqt-git/liblxqt-git-0.13.0.110.g0a6ae1d-1-x86_64.pkg.tar.xz'), '-I', PosixPath('/home/lilydjwg/archgitrepo/lxqt-build-tools-git/lxqt-build-tools-git-0.5.0.16.g72e5bf0-1-any.pkg.tar.xz'), '-d', '/home/lilydjwg/.cargo:/build/.cargo', '--', '--holdver'] 返回了错误号 255。命令的输出如下：

:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:green;">==&gt;</span><span style="font-weight:bold;"> Building in chroot for [extra] (x86_64)...</span>
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:green;">==&gt;</span><span style="font-weight:bold;"> Synchronizing chroot copy [/var/lib/archbuild/extra-x86_64/root] -&gt; [lilydjwg]...</span><span style="font-weight:bold;">done</span>
loading packages...
resolving dependencies...
:: There are 2 providers available for libgl:
:: Repository extra
   1) libglvnd  2) nvidia-340xx-utils

Enter a number (default=1): 
warning: cannot resolve &quot;libqtxdg-git&quot;, a dependency of &quot;liblxqt-git&quot;
warning: cannot resolve &quot;liblxqt-git&quot;, a dependency of &quot;lxqt-globalkeys-git&quot;
warning: cannot resolve &quot;libqtxdg-git&quot;, a dependency of &quot;liblxqt-git&quot;
:: The following packages cannot be upgraded due to unresolvable dependencies:
      lxqt-globalkeys-git  liblxqt-git

:: Do you want to skip the above packages for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'libqtxdg-git' required by liblxqt-git
:: unable to satisfy dependency 'liblxqt-git' required by lxqt-globalkeys-git
:: unable to satisfy dependency 'libqtxdg-git' required by liblxqt-git
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:green;">==&gt;</span><span style="font-weight:bold;"> Making package: lxqt-panel-git 0.13.0.1103.g5c4e722a-1 (Tue Dec 11 11:31:35 2018)</span>
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:green;">==&gt;</span><span style="font-weight:bold;"> Retrieving sources...</span>
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:blue;">  -&gt;</span><span style="font-weight:bold;"> Updating lxqt-panel git repo...</span>
Fetching origin
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:green;">==&gt;</span><span style="font-weight:bold;"> Validating source files with sha256sums...</span>
    lxqt-panel ... Skipped
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:green;">==&gt;</span><span style="font-weight:bold;"> Making package: lxqt-panel-git 0.13.0.1103.g5c4e722a-1 (Tue 11 Dec 2018 11:31:37 AM CST)</span>
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:green;">==&gt;</span><span style="font-weight:bold;"> Checking runtime dependencies...</span>
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:green;">==&gt;</span><span style="font-weight:bold;"> Installing missing dependencies...</span>
error: target not found: libsysstat-git
error: target not found: lxqt-globalkeys-git
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:red;">==&gt; ERROR:</span><span style="font-weight:bold;"> 'pacman' failed to install missing dependencies.</span>
<span style="font-weight:bold;"></span><span style="font-weight:bold;color:red;">==&gt; ERROR:</span><span style="font-weight:bold;"> Build failed, check /var/lib/archbuild/extra-x86_64/lilydjwg/build</span>

调用栈如下：

Traceback (most recent call last):
  File &quot;/home/lilydjwg/soft/lilac/lilac&quot;, line 89, in build_package
    bindmounts = BIND_MOUNTS,
  File &quot;/home/lilydjwg/soft/lilac/lilac2/building.py&quot;, line 72, in lilac_build
    build_prefix, depend_packages, bindmounts, makechrootpkg_args)
  File &quot;/home/lilydjwg/soft/lilac/lilac2/building.py&quot;, line 117, in call_build_cmd
    build_output = run_cmd(cmd, use_pty=True)
  File &quot;/home/lilydjwg/soft/lilac/lilac2/cmd.py&quot;, line 103, in run_cmd
    raise subprocess.CalledProcessError(code, cmd, outs)
subprocess.CalledProcessError: Command '['extra-x86_64-build', '--', '-I', PosixPath('/home/lilydjwg/archgitrepo/libsysstat-git/libsysstat-git-0.4.1.4.gef0e4de-1-x86_64.pkg.tar.xz'), '-I', PosixPath('/home/lilydjwg/archgitrepo/lxqt-globalkeys-git/lxqt-globalkeys-git-0.13.0.76.g7ac6ecb-1-x86_64.pkg.tar.xz'), '-I', PosixPath('/home/lilydjwg/archgitrepo/liblxqt-git/liblxqt-git-0.13.0.110.g0a6ae1d-1-x86_64.pkg.tar.xz'), '-I', PosixPath('/home/lilydjwg/archgitrepo/lxqt-build-tools-git/lxqt-build-tools-git-0.5.0.16.g72e5bf0-1-any.pkg.tar.xz'), '-d', '/home/lilydjwg/.cargo:/build/.cargo', '--', '--holdver']' returned non-zero exit status 255.
</pre>

@petronny: summary & details~

**Comment by lilydjwg** [comment]
@yan12125 这是什么时候的日志？

**Comment by yan12125** [comment]
我從我的信箱複製出來的。編譯機上的話是從`lilac-log/2018-12-11T09:03:01`這個檔案的146379行開始。

**Comment by yan12125** [comment]
我在我的機器上跑`test-lilac-dep.py`，的確少了一個包：
```
$ PYTHONPATH=./vendor python t.py
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/liblxqt-git'), pkgname='liblxqt-git')
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/lxqt-build-tools-git'), pkgname='lxqt-build-tools-git')
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/libsysstat-git'), pkgname='libsysstat-git')
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/lxqt-globalkeys-git'), pkgname='lxqt-globalkeys-git')
```
百合是不是有些code沒有commit上去？

lilac: 9ce5f09dbb294e7d2ab662976b0dea23d2f89515 with archlinuxcn/repo@68142e1a4a69081bb93890826a604b52c5ede77c

**Comment by lilydjwg** [comment]
同样的 commit，结果不同……大概和加载顺序有关。

**Comment by yan12125** [comment]
FWIW, 我的機器上順序是這樣：
```
libsysstat-git
lxqt-build-tools-git
libqtxdg-git
lxqt-globalkeys-git
lxqt-panel-git
liblxqt-git
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/lxqt-globalkeys-git'), pkgname='lxqt-globalkeys-git')
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/liblxqt-git'), pkgname='liblxqt-git')
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/libsysstat-git'), pkgname='libsysstat-git')
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/lxqt-build-tools-git'), pkgname='lxqt-build-tools-git')
```
(我在lilacpy.py裡，load_lilac()之前加print)

**Comment by lilydjwg** [comment]
```
libsysstat-git
lxqt-build-tools-git
liblxqt-git
libqtxdg-git
lxqt-globalkeys-git
lxqt-panel-git
```

果然……

**Comment by lilydjwg** [comment]
@yan12125 试试 1c3dd4a15fd65e934ecee30a1bbf4221006b0e2e？

**Comment by yan12125** [comment]
It works :)
```
libsysstat-git
lxqt-build-tools-git
libqtxdg-git
lxqt-globalkeys-git
lxqt-panel-git
liblxqt-git
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/liblxqt-git'), pkgname='liblxqt-git')
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/lxqt-build-tools-git'), pkgname='lxqt-build-tools-git')
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/lxqt-globalkeys-git'), pkgname='lxqt-globalkeys-git')
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/libqtxdg-git'), pkgname='libqtxdg-git')
Dependency(pkgdir=PosixPath('../aur/archlinuxcn-repo/libsysstat-git'), pkgname='libsysstat-git')
```
